[manager]
ratio = [1, 2, 3]
show_hidden = true
linemode = "size"

[preview]
max_width = 1000
max_height = 1000

# [plugin]
# prepend_previewers = [
#   { name = "*.md", run = "glow" },
# ]

# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*"
# run  = "git"
#
# [[plugin.prepend_fetchers]]
# id   = "git"
# name = "*/"
# run  = "git"
