#!/usr/bin/env bash

apt update

apt install -y git curl neovim zsh tmux ranger fzf stow

stow zsh nvim

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended

stow oh-my-zsh

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

stow config

~/.config/tmux/plugins/tpm/bin/install_plugins
