#!/usr/bin/env bash

# apps
brewApps=(clang-format neovim)
brewCasks=(font-dejavu-sans-mono-nerd-font rectangle)
nixApps=(tmux ranger fzf stow make unzip)
nvimNixApps=(
	lua-language-server-3.13.6
	ccls-0.20241108
	typescript-5.9.3
	typescript-language-server-5.1.3
	vscode-langservers-extracted-4.10.0
)

clone() {
	git clone "https://github.com/$1" "$2"
}

isInstalled() {
	command -v "$1" &>/dev/null
}

# install git if not present && not mac
if ! isInstalled git && [[ "$(uname)" != "Darwin" ]]; then
	echo "here"
	apt update
	apt install -y git
fi

clone 'cviejo/dotfiles' ~/.dotfiles
cd ~/.dotfiles || exit

if [[ "$(uname)" == "Darwin" ]]; then
	brew install "${brewApps[@]}"
	brew install --cask "${brewCasks[@]}"
	nix-env -i "${nixApps[@]}" "${nvimNixApps[@]}"
else
	apt update
	apt install -y git curl zsh "${brewApps[@]}" "${nixApps[@]}"
fi

chsh -s "$(which zsh)"
stow zsh nvim bin

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended

stow oh-my-zsh

zshPlugins=~/.oh-my-zsh/custom/plugins
clone 'zsh-users/zsh-autosuggestions' "${zshPlugins}/zsh-autosuggestions"
clone 'zsh-users/zsh-syntax-highlighting.git' "${zshPlugins}/zsh-syntax-highlighting"
clone 'Aloxaf/fzf-tab' "${zshPlugins}/fzf-tab"
clone 'jeffreytse/zsh-vi-mode' "${zshPlugins}/zsh-vi-mode"

tmuxPlugins=~/.config/tmux-plugins
clone 'tmux-plugins/tpm' "${tmuxPlugins}/tpm"

stow config

source ~/.zshrc

# curl -fsSL https://fnm.vercel.app/install | bash
# fnm install --lts

"${tmuxPlugins}/tpm/bin/install_plugins"
