#!/usr/bin/env bash

dotfiles=~/.dotfiles
github=https://github.com
zshplugins=~/.oh-my-zsh/custom/plugins
tmuxplugins=~/.config/tmux-plugins

git clone ${github}/cviejo/dotfiles ${dotfiles}

apt update

apt install -y git curl neovim zsh tmux ranger fzf stow

cd ${dotfiles}

stow zsh nvim

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended

stow oh-my-zsh

git clone ${github}/zsh-users/zsh-autosuggestions ${zshplugins}/zsh-autosuggestions
git clone ${github}/zsh-users/zsh-syntax-highlighting.git ${zshplugins}/zsh-syntax-highlighting
git clone ${github}/Aloxaf/fzf-tab ${zshplugins}/fzf-tab

git clone ${github}/tmux-plugins/tpm ${tmuxplugins}/tpm

stow config

${tmuxplugins}/tpm/bin/install_plugins

nvim --headless -es -c "lua require('utils.install-packer')"
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
